version: '3.8'

services:
  gin-server:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      REDIS_ADDR: redis:6379
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"
